<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    
    
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.5" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CleanSync.Application\CleanSync.Application.csproj" />
    <ProjectReference Include="..\CleanSync.Infrastructure\CleanSync.Infrastructure.csproj" />
    <ProjectReference Include="..\CleanSync.Domain\CleanSync.Domain.csproj" />
  </ItemGroup>

</Project>
